### ISSUE TITLE
Revamp Infra

### ISSUE THREAD

**Issue by nhz-io** [ironSource/node-regedit#27]
# Project infra revamp

- [x] #28 add appveyor.yml
- [ ] #29 configure [appveyor](https://ci.appveyor.com/project/ironSource/node-regedit) (project and tokens)
- [x] #30 add linter
- [x] #31 add pre-push hooks

**Comment by nhz-io** [comment]
# Project infra revamp

Need to:
* add appveyor.yml
* configure appveyor (project and tokens)
* add linter
* add pre-push hooks
